---

kube_version: v1.9.1
token: b0f7b8.8d1767876297d85c

# 1.8.x feature: --feature-gates SelfHosting=true
init_opts: ""

# Any other additional opts you want to add.. 
kubeadm_ops: ""
# For example:
# kubeadm_opts: '--apiserver-cert-extra-sans "k8s.domain.com,kubernetes.domain.com"'

service_subnet: 10.96.0
service_cidr: "{{ service_subnet }}.0/12"
dns_name: cluster.local
dns_ip: "{{ service_subnet }}.10"

# Network implementation('flannel')
network: flannel
pod_network_cidr: 10.244.0.0/16

# A list of insecure registrys you might need to define
insecure_registrys:
# - "gcr.io"
