- hosts: all

  become: yes

  tasks:
    - name: Upgrade all packages to the latest version
      apt: update_cache=yes upgrade=dist

    - name: Update APT package cache
      action: apt update_cache=yes

    - name: Install list of packages
      apt: name={{item}} state=present
      with_items:
           - sudo
           - curl
           - vim
           - make
           - apt-transport-https
           - ca-certificates 
           - gnupg2
           - software-properties-common

    - name: Add Docker signing key, will not download if present
      apt_key:
        id: 0EBFCD88
        url: https://download.docker.com/linux/debian/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/debian buster edge
        state: present

    - name: Install Docker
      apt:
        name: docker-ce
        state: present
        update_cache: yes

    - name: Make sure Docker group exists
      group: 
        name="docker"
        state=present

    - name: Add current user to docker group
      user: 
        name="{{ ansible_user_id }}"
        state=present
        append=yes
        groups=docker
        shell=/bin/bash
