- hosts: all
  # user: root
  become: yes
  become_method: su
  become_user: root

  vars:
    - create_user: docker

  tasks:
    - name: Upgrade all packages to the latest version
      apt: update_cache=yes upgrade=dist

    - name: Update APT package cache
      action: apt update_cache=yes

    - name: Install list of packages
      apt: name={{item}} state=installed
      with_items:
           - sudo
           - curl
           - vim
           - make
           - apt-transport-https
           - ca-certificates 
           - gnupg2
           - software-properties-common

    - name: Add Docker signing key, will not download if present
      apt_key:
        id: 0EBFCD88
        url: https://download.docker.com/linux/debian/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/debian stretch edge
        state: present

    - name: Install Docker
      apt:
        name: docker-ce
        state: present
        update_cache: yes

    - name: Create a docker group
      group: 
        name="{{ create_user }}"
        state=present

    - name: Create a new user
      user: 
        name="{{ create_user }}"
        state=present
        groups="sudo,docker"
        shell=/bin/bash

    # Add the user to wheel for passwordless sudo
    # make sure that root ssh is disabled as well
    - include: ../tasks/ssh-and-wheel.yaml


  handlers:
    - name: restart networking
      service: name=networking state=restarted
    - name: restart ssh
      service: name=sshd state=restarted
