- hosts: all
  # user: root
  become: yes
  become_method: su
  become_user: root

  vars:
    default_if: enp2s0
    create_user: libvirt

  tasks:

    - name: Upgrade all packages to the latest version
      apt: update_cache=yes upgrade=dist

    - name: Update APT package cache
      action: apt update_cache=yes

    - name: Install bridge-utils
      apt: name=bridge-utils state=present

    - name: Setup bridge br0 where the interface connects to this bridge
      template: src=../templates/interfaces.br0 dest=/etc/network/interfaces

    - name: Install list of packages
      apt: name={{item}} state=installed
      with_items:
           - sudo
           - curl
           - vim
           - make

    - name: Install kvm
      apt: name={{item}} state=installed
      with_items:
           - qemu-kvm
           - libvirt-clients
           - libvirt-daemon-system
           - virtinst

    - name: Create a new user and add user to libvirt groups
      user: 
        name="{{ create_user }}"
        state=present
        groups="sudo,libvirt,libvirt-qemu"
        shell=/bin/bash

    # Required due to default routes on Debian 9 installation
    - name: Install iptables-persistent
      apt: name={{item}} state=installed
      with_items:
        - iptables-persistent
    - name: Allow forward to br0
      shell: touch /etc/iptables/rules.v4 && iptables -A FORWARD -p all -i br0 -j ACCEPT && iptables-save > /etc/iptables/rules.v4

    # Add the user to wheel for passwordless sudo
    # make sure that root ssh is disabled as well
    - include: ../tasks/ssh-and-wheel.yaml

  handlers:
    - name: restart ssh
      service: name=sshd state=restarted
