---

- name: Reset Kubernetes component
  shell: "kubeadm reset"
  register: reset_cluster

- name: Init Kubernetes cluster
  when: reset_cluster|succeeded
  shell: |
    kubeadm init --service-cidr {{ service_cidr }} \
                 --kubernetes-version {{ kube_version }} \
                 --pod-network-cidr {{ pod_network_cidr }} \
                 --token {{ token }} \
                 {{ kubeadm_opts }} \
                 {{ init_opts }}
  register: init_cluster

- name: Create Kubernetes config directory
  file: path=/{{ ansible_user_id }}/.kube/ state=directory

- name: Copy admin.conf to Home directory
  when: init_cluster
  copy:
    src: "{{ kubeadmin_config }}"
    dest: "/{{ ansible_user_id }}/.kube/config"
    owner: {{ ansible_user_id }}
    group: {{ ansible_user_id }}
    mode: 0755
    remote_src: True

- name: Enable and restart kubelet engine
  systemd:
    name: kubelet
    daemon_reload: yes
    state: restarted
    enabled: yes
  register: started_kubelet
