- hosts: all
  become: yes

  tasks:

    - name: Install sudo
      apt:
        name: sudo
        state: present
        update_cache: yes

    - name: Make sure we have a 'wheel' group
      group:
        name: wheel
        state: present

    - name: Allow 'wheel' group to have passwordless sudo
      lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: '^%wheel'
        line: '%wheel ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'

    - name: Create the user
      user: 
        name="{{ create_user }}"
        state=present
        groups="sudo"
        shell=/bin/bash

    - name: Placing key
      authorized_key: user="{{ create_user }}" key="{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

    - name: Add sudoers users to wheel group
      user: name="{{ create_user }}" groups=wheel append=yes state=present createhome=yes

    - name: Disallow password authentication
      action: lineinfile dest=/etc/ssh/sshd_config regexp="^PasswordAuthentication" line="PasswordAuthentication no" state=present
      notify: restart ssh

    - name: Disallow root SSH access
      action: lineinfile dest=/etc/ssh/sshd_config regexp="^PermitRootLogin" line="PermitRootLogin no" state=present
      notify: restart ssh


  handlers:
    - name: restart ssh
      service: name=sshd state=restarted
